# permissions for end users to view middlewareclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: middlewareclaim-viewer-role
rules:
- apiGroups:
  - core.my.domain
  resources:
  - middlewareclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.my.domain
  resources:
  - middlewareclaims/status
  verbs:
  - get
