# permissions for end users to view middlewarepolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: middlewarepolicy-viewer-role
rules:
- apiGroups:
  - core.my.domain
  resources:
  - middlewarepolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.my.domain
  resources:
  - middlewarepolicies/status
  verbs:
  - get
