# permissions for end users to edit middlewarepolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: middlewarepolicy-editor-role
rules:
- apiGroups:
  - core.my.domain
  resources:
  - middlewarepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.my.domain
  resources:
  - middlewarepolicies/status
  verbs:
  - get
