# permissions for end users to edit middlewares.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: middleware-editor-role
rules:
- apiGroups:
  - core.my.domain
  resources:
  - middlewares
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.my.domain
  resources:
  - middlewares/status
  verbs:
  - get
