# permissions for end users to edit mysqls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysql-editor-role
rules:
- apiGroups:
  - middleware.my.domain
  resources:
  - mysqls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - middleware.my.domain
  resources:
  - mysqls/status
  verbs:
  - get
