apiVersion: core.my.domain/v1alpha1
kind: Middleware
metadata:
  name: middleware-sample
spec:
  selector:
    matchLabels:
      release: "stable"
    matchExpressions:
      - { key: environment, operator: In, values: [ dev ] }
  resources:
    storage: 8Gi
    connection: 2000
  connInfo:
    secret: user-a
